version: '3.8'

services:
  backendtest:
    build: 
      context: kasintu
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    restart: always
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/kasintu_test
      - SPRING_DATASOURCE_PASSWORD=root