version: '3.8'

services:
  db:
    image: mysql
    ports:
      - '3307:3306'
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE: 'kasintu'

  backend:
    build: .
    ports:
      - '8080:8080'
    restart: always
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/kasintu
      - SPRING_DATASOURCE_PASSWORD=root